### ISSUE TITLE
Unable to Create Links to New TLDs - 241 Missing Since Last Sync

### ISSUE THREAD

**Issue by cmarin** [twitter/twitter-text#113]
A number of people recently tried to include this link in a Tweet under a gTLD my company owns:
http://i.am.csc

We were surprised to find out that it didn't work (the traffic was directed to http://i.am).  In digging into this a bit more it appears that the problem can be traced back to this file, which seems to control the TLDs used by Twitter (last updated by @jakl):
https://github.com/twitter/twitter-text/blob/master/conformance/tld_lib.yml

As you can see it has not been updated since Aug 25, 2015.  However, according to ICANN there have been 241 TLDs launched since that time:
https://newgtlds.icann.org/en/program-status/delegated-strings

That means that companies from Apple (http://nic.apple) to Audi (http://nic.audi) and others are being affected by these omissions.  If you could resync this file with the latest list from IANA, or at the very least manually add .csc we would really appreciate it.

I've attached a spreadsheet of the delegated string from that ICANN link in case that helps.

Thanks in advance!
[icann_tlds.xlsx](https://github.com/twitter/twitter-text/files/224826/icann_tlds.xlsx)

**Comment by toddlevy** [comment]
+1

Adding a link to the IANA Root Zone Database...
http://www.iana.org/domains/root/db
... which I believe is referenced at the top of the tld_lib file mentioned above.

**Comment by changok** [comment]
Resolved by #125
