### ISSUE TITLE
Highlight text that is too long (javascript)

### ISSUE THREAD

**Issue by rourke** [twitter/twitter-text#124]
I can't find any help documentation so I want to ask this here. I want to have an emphasis tag on the part of the tweet that is exceeding the 140 character limit. How would I do this with javascript?

**Comment by ianmobbs** [comment]
If `tweet` is a String containing your characters, you could divide it into two strings using the `.substring(start, end)` method, which you can read about [here](http://www.w3schools.com/jsref/jsref_substring.asp). However, questions such as these aren't necessarily issues with the repository, and should be asked in development forums such as StackOverflow!
