### ISSUE TITLE
More TLDs to add. Oh joy.

### ISSUE THREAD

**Issue by edent** [twitter/twitter-text#134]
As per #44 and #55 

https://data.iana.org/TLD/tlds-alpha-by-domain.txt was updated on Wed Jul 27th 2016.

I'm not quite sure when you last did an update, but I believe you are missing the following.

```
+AMERICANFAMILY
+AMFAM
+BESTBUY
+BOOKING
+CITADEL
+DOCTOR
+DUCK
+DUNS
+ESURANCE
+HONEYWELL
+IEEE
+LPL
+LPLFINANCIAL
+MSD
+OFF
+RAID
+RIGHTATHOME
+SCJOHNSON
+SWIFTCOVER
+TIAA
```

**Comment by codemonkey3045** [comment]
Will update these in the next release - shouldn't take more than 2 weeks to put together and deploy. Thanks @edent!

**Comment by edent** [comment]
I'm sure there'll be even more in a few weeks 😆
