### ISSUE TITLE
Swift support?

### ISSUE THREAD

**Issue by netgfx** [twitter/twitter-text#135]
Will this support Swift eventually or be ported into Swift?

**Comment by andypiper** [comment]
I'm not aware of any plans to add Swift support specifically - in the case of e.g. PHP and some others, there are some third party re-implementations even though they are not included in this library.

**Comment by codemonkey3045** [comment]
Still not in our plans :(

**Comment by annjawn** [comment]
Hi, I am trying to find some help in adding this library to a Swift project and I am facing issues with the Bridging headers etc. I am sure I am not doing it correctly, but is anyone aware on how to get it setup in a Swift project?
