### ISSUE TITLE
"stars.now" content is not considered as a link.

### ISSUE THREAD

**Issue by GowthamanMadhu** [twitter/twitter-text#136]
The Content: stars.now it's considered as a link (23 characters) on the Twitter website. But in these resources the above content considers as a normal text (9 characters).

Kindly do the needful.

**Comment by andypiper** [comment]
I've just tried this with the current version of the Javascript library and stars.now is indeed recognised as a link. Can you provide a code example that does not work?

**Comment by GowthamanMadhu** [comment]
@andypiper Thanks for your response. I have attached source file. 
[TweetValidator.txt](https://github.com/twitter/twitter-text/files/421762/TweetValidator.txt)

**Comment by andypiper** [comment]
I don't know what version of the code that is, but if you look at [the current source of twitter-text.js](https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js) you'll find that it does include the .now TLD as a valid domain. Update to twitter-text 1.14 which is more recent than the code you're trying to use.

**Comment by GowthamanMadhu** [comment]
@andypiper he latest version sources of twitter-text.js working fine. Thanks for your help.
