### ISSUE TITLE
Support for 140 characters limit change

### ISSUE THREAD

**Issue by Tyny** [twitter/twitter-text#138]
Hey there,

  First of all, thanks, you guys saved me a lot of time!

  Are you planning to support this? For statuses update and replies ?https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

  If you are, can I have an estimate time?

Thanks!

**Comment by andypiper** [comment]
This is covered in the answer to #117

**Comment by Tyny** [comment]
@andypiper Thanks!
