### ISSUE TITLE
Twitter's new, longer tweets are coming September 19th

### ISSUE THREAD

**Issue by GowthamanMadhu** [twitter/twitter-text#141]
Dear Team,
Any update about the longer tweets?

http://www.theverge.com/platform/amp/2016/9/12/12891562/twitter-tweets-140-characters-expand-photos
https://blog.twitter.com/express-even-more-in-140-characters

Thanks,
Madhubala.

**Comment by andypiper** [comment]
First of all, the twitter-text library is intended to validate Tweet text content. Given the server-side nature of [most of the API changes we've already documented](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets), we [currently have no plans to modify](https://github.com/twitter/twitter-text/issues/117) the twitter-text library.

The issues section of this Github repo is not an appropriate place to ask this question. You'll find the [latest status on this in our developer forums](https://twittercommunity.com/t/additional-updates-to-new-tweet-api-options/73933). Thank you.
