### ISSUE TITLE
getTweetLength not working

### ISSUE THREAD

**Issue by sridharkalaibala** [twitter/twitter-text#142]
If text has link without http  `google.com/contact`  . getTweetLength is not returning correct value.

**Comment by codemonkey3045** [comment]
A url without protocol should count as 23 characters. See our test here:
https://github.com/twitter/twitter-text/blob/master/conformance/validate.yml#L230

<img width="537" alt="screen shot 2016-10-20 at 10 50 40 pm" src="https://cloud.githubusercontent.com/assets/1509085/19588012/abfb7fd8-9717-11e6-80dd-3407f22f2029.png">

140 - 117 = 23 characters. 

@sridharkalaibala, please reopen this ticket if you're getting something else and we'll debug.
