### ISSUE TITLE
Latin Accented Characters in Hashtags

### ISSUE THREAD

**Issue by rafitorres** [twitter/twitter-text#145]
Looks like autolink (at least the JS version) isn't correctly detecting hashtags with latin accented characters. 

Tweet example: https://twitter.com/Agroaguadia/status/774345488560754689 

On Twitter, the full #DíaDeLaAgricultura tag is detected. Twitter-text only detects #D

**Comment by ay8s** [comment]
Seeing the same with the Objective-C implementation.

**Comment by codemonkey3045** [comment]
` - description: "Extract a hashtag containing é"
      text: "Working remotely #café"
      expected: ["café"]`

https://github.com/twitter/twitter-text/blob/master/conformance/extract.yml#L636
that's a test currently passing. What version of twitter-text are you guys running?

**Comment by ay8s** [comment]
Hey @codemonkey3045. False alarm on my side. Looks like it's working correctly and was related to needing to encode the entity before passing to NSURL on the Objective-C side. 👍
