### ISSUE TITLE
Update to use new Twitter counting algorithm

### ISSUE THREAD

**Issue by shermmyy** [twitter/twitter-text#146]
Tiwtter updated how they count media as characters

reference: 
https://twittercommunity.com/t/new-attachment-url-option-is-now-live-on-the-tweet-endpoints/74270

**Comment by andypiper** [comment]
If you include URLs in your Tweet text, characters are counted in exactly the same way. If you use the new parameters, you can count the Tweet text without the URLs. There's no specific change required here that we are aware of at present. See #117 for more discussion.
