### ISSUE TITLE
1.14.1 tag not created 

### ISSUE THREAD

**Issue by xiao99xiao** [twitter/twitter-text#151]
1.14.1 tag not created, which caused CocoaPods generating error saying 'Could not find remote branch v1.14.1 to clone'.

**Comment by ay8s** [comment]
Just hit the same, @codemonkey3045 wondering if its possible to tag the latest release to fix up Cocoapod updates?

**Comment by codemonkey3045** [comment]
will do! Sorry about that!

**Comment by codemonkey3045** [comment]
@xiao99xiao @ay8s The tag's created. I'm still in the process of merging it into all of the internal Twitter projects so I'm leaving it as a pre-release tag for now and will toggle it when everything's on the newest twitter-text version. Reopen this if it's still a problem.

**Comment by ay8s** [comment]
Thanks @codemonkey3045. Working perfectly now. 👍
