### ISSUE TITLE
Non-breaking hyphen breaks urls

### ISSUE THREAD

**Issue by gazay** [twitter/twitter-text#155]
Medium supports non-breaking hyphen for slug generation (https://medium.com/russian/о-кино-книгах-и-грамотности-7519c9734d01#.3q3z5fbr6 for example – the first three `-` are nb hyphens and last two – just normal ones `-`. I don't know why). And this kind of links would be broken in twitter and all soft which uses this library. And still, this is a valid link and it will transfer you to target medium article. Maybe we should add this symbol in regex? I can do a PR and test case for this

**Comment by codemonkey3045** [comment]
Thanks for opening the issue. I'll try to replicate and prioritize this when I get a moment. 

PRs and test cases are definitely welcome :)

**Comment by leeaustinadams** [comment]
Appears to be fixed
