### ISSUE TITLE
npm WARN install: Refusing to install twitter-text as a dependency of itself

### ISSUE THREAD

**Issue by jm3** [twitter/twitter-text#16]
upon following the npm install instructions in [README.md](https://github.com/twitter/twitter-text/blob/master/js/README.md): `npm install twitter-text`:

```
npm WARN install Refusing to install twitter-text as a dependency of itself
```

**Comment by OClement** [comment]
@jm3 
You probably did the same as I did for another package I wanted to try (jspm):

```
$ mkdir twitter-text
$ cd twitter-text
$ npm init
Answered everything by default of whatever
```

Now, your `package.json` has a `"name":"twitter-text"` property

When doing `npm install twitter-text`, NPM thinks you are trying to install the package in itself, becuase of that name.

Just rename this field and everything should fly
---

Definitely not a problem with `twitter-text`

**Comment by wumble** [comment]
thanks for this!
