### ISSUE TITLE
Symlink destination does not exist, so that require fails

### ISSUE THREAD

**Issue by Nyoho** [twitter/twitter-text#162]
Just doing ``require 'twitter-text'`` fails because symbolic link destination of``lib/assets/tld_lib.yml`` that is ``lib/assets/../../../conformance/tld_lib.yml`` does not exsit as follows.

```
/Users/nyoho/.rbenv/versions/2.3.3/lib/ruby/2.3.0/psych.rb:474:in `initialize': No such file or directory @ rb_sysopen - /Users/nyoho/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/twitter-text-1.14.3/lib/assets/tld_lib.yml (Errno::ENOENT)
```

It occurs from version ``1.14.3``.
It might be better to replace the symlink with a real file. (?)

**Comment by codemonkey3045** [comment]
Thanks for filing a ticket. I'll look into it shortly! 
Btw, take caution with 1.14.3. It's still in pre-release / testing mode.

**Comment by codemonkey3045** [comment]
Did this not occur in 1.14.2? I don't remember any changes that might have caused this.

**Comment by Nyoho** [comment]
It didn't occur in 1.14.2. (I have used twitter-text from another gem for long time.)
But yesterday I noticed the following.

Designating 1.14.2 in Gemfile and doing ``bundle install``, it didn't occur in 1.14.2.
But after uninstalling, doing ``gem install twitter-text -v 1.14.2`` causes the error. (The non-exsistence symlink destination)

**Comment by arronmabrey** [comment]
Our team is dealing with the same issue. twitter-text was bumped from 1.14.2 to 1.14.3 then our ci builds started failing.

**Comment by arronmabrey** [comment]
Looks like there are two other github references to this issue as well. 
- https://github.com/ryota-ka/twterm/issues/286
- https://github.com/longhotsummer/slaw/commit/b9ad61cda0aadc5d16cb81265b767cfff5a81ce7

**Comment by arronmabrey** [comment]
I agree with @codemonkey3045, I just looked through the [diffs of `v1.14.2` and `v1.14.3`](https://github.com/twitter/twitter-text/compare/v1.14.2...v1.14.3) and I didn't see anything immediately jump out that would cause this issue. Seems like there is something more sneaky at play here.

**Comment by ryangreenberg** [comment]
I think this problem is caused by a change in how Rubygems handles symlinks when it creates .gem files (when `gem build` is run).

v1.14.2 contains an actual yml file, and v1.14.3 contains a (broken) symlink, and there was no change to the underlying files in between versions.

In twitter-text/rb I ran:
```
ruby --version && gem --version && gem build twitter-text.gemspec && tar --to-stdout -xf twitter-text-1.14.3.gem data.tar.gz | tar -vzt
```

With rubygems 2.4.5 I get:

```
2.4.5
...
  Successfully built RubyGem
  Name: twitter-text
  Version: 1.14.3
  File: twitter-text-1.14.3.gem
...
-rw-rw----  0 wheel  wheel   13334 Jan 11 11:25 lib/assets/tld_lib.yml
```

With 2.6.8 (the most recent) I get:

```
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]
2.6.8
...
  Successfully built RubyGem
  Name: twitter-text
  Version: 1.14.3
  File: twitter-text-1.14.3.gem
...
lrwxrwx---  0 wheel  wheel       0 Jan 11 11:22 lib/assets/tld_lib.yml -> lib/assets/../../../conformance/tld_lib.yml

```

**Comment by codemonkey3045** [comment]
Thanks @ryangreenberg! I got 1.14.5 built on rubygems 2.4.5
```
tar --to-stdout -xf twitter-text-1.14.5.gem data.tar.gz | gunzip | tar -tv
...
-rw-r--r--  0 wheel  wheel   13334 Jan 11 11:53 lib/assets/tld_lib.yml
```

@arronmabrey, @Nyoho want to give version 1.14.5 a try?

**Comment by Nyoho** [comment]
I checked it and that's OK! Thank you @codemonkey3045!

**Comment by ryangreenberg** [comment]
Without digging into the history of changes to rubygems, my guess is that https://github.com/rubygems/rubygems/pull/1209 is part of the reason the strategy used in twitter-text no longer works. twitter-text relies on the behavior where `gem build` includes the targets of symlinks in the gem directly. The behavior of current versions of rubygems is to include the symlinks themselves, which fails for the reasons detailed here. 

While it would be nice to have an option to follow (or not follow) symlinks when running `gem build`, the easiest workaround is probably to copy the symlinked file into the gem as part of the build process.
