### ISSUE TITLE
Feature Request: Twitter Handle from Twitter Profile URL

### ISSUE THREAD

**Issue by stevendelarwelle** [twitter/twitter-text#163]
Could you add a feature to extract twitter handles from a twitter url?

**Comment by codemonkey3045** [comment]
This library's focus is to parse text within a tweet and identify linkable components (mentions, hashtags, urls, cashtags). @stevendelarwelle, could you elaborate your request with maybe an example or 2?

**Comment by stevendelarwelle** [comment]
for instance you have the url http://www.twitter.com/username
return username

**Comment by codemonkey3045** [comment]
Before adding new features to a library, I like to figure out a few questions:
- Why should we add that feature to this specific library? 
- Does it belong here?
- What current problem/bug does it solve?

It's nice to keep libraries as small and focused as possible. If you or someone else can make a case for it, I'm listening and accepting pull requests :)

**Comment by stevendelarwelle** [comment]
1. So the users of the library with a list of user profiles can extract the usernames and tweet at them.
2. Yes, it's the exact same thing you're doing with the text of the tweet.
3. It solves the problem of writing extra code to get the username and using this library to tweet at somebody from an application or creating tweet links if you have a list of twitter profiles.

**Comment by twuttke** [comment]
Hi,

We don't want to add rarely used things to this library to keep it compact.
It is already too big, IMO.

1. When do people obtain a list of profile urls as opposed to screen names?
I'm curious where you are getting those from.
2. It's not the exact same thing. A Twitter profile URL is not identified
inside of twitter text. What twitter text identifies is a valid screen name
preceded by @ and having the proper edge cases. It also identifies a valid
General URLs for linking, but does not special case profile urls.
3. Your use case seems application-specific, and could done in one line of
code:

// Returns the screen name of the profile url, or empty string if the
profile url is invalid
function screenNameFromTwitterProfileUrl(profileUrl) {
  return profileUrl.replace(/^https?:\/\/twitter.com\/(\w{1,15})$|.*/,
'$1');
}

Is that helpful?

- Tom
