### ISSUE TITLE
Is there a way to extract text if charcter length is given

### ISSUE THREAD

**Issue by dineshvgp** [twitter/twitter-text#164]
I need to extract exactly the 140 chars based on twitter-text length algorithm. Is there a way to extract only the first 140 chars of given text?

**Comment by twuttke** [comment]
Not a good way, no. There's a couple of problems. The first is if you're
using JavaScript you need to snip the string before or after a surrogate
pair, but in the middle, in case there is an astral plane Emoji in there or
something. The next problem is if there are URLs in there they will get
Rewritten as 23 character tokenized URLs, so if they go one character over
you might want to snip before the entire URL started. You might also want
to avoid cutting a username or a hashtag in half.

Depending on how you want to handle those cases there's different ways of
writing this.

A very rudimentary algorithm might do a length calculation and then if it
is greater than 140, remove the last entity or code point and try again.
When I say code point, I mean a character or surrogate pair depending on
what the Unicode ranges. When I say entity I mean you are all or hashtag or
mention handle.

If you need something higher performance you could write something with
more logic in it.

Tom
