### ISSUE TITLE
add js to bower

### ISSUE THREAD

**Issue by luisrudge** [twitter/twitter-text#18]
please add this to bower. thanks!

**Comment by HamletDRC** [comment]
@luisrudge You can always add the git commit into your bower.json... 


    "twitter-text": "git+https://github.com/twitter/twitter-text.git#de3cdbc675d22aacf4ccdfb04eeac97cf4ace2b5",

**Comment by luisrudge** [comment]
Yeah. That's the beauty of bower :)

**Comment by jakl** [comment]
Bower added.
