### ISSUE TITLE
Add support for og:image 

### ISSUE THREAD

**Issue by sshcli** [twitter/twitter-text#180]
I'm not sure if this is the right repository to report this, 
Just close this issue if it is not.

I'm not reporting a bug, this is more like an enhance suggestion for twitter.
Most popular social networks around there are already loading images automatically when insert a link in the post.

Twitter doesn't have this option yet, and open graph protocol could help (og:image)

Again, please close this issue if this is not the right place to report this.

Regards,

**Comment by andypiper** [comment]
[Twitter Cards](https://dev.twitter.com/cards/overview) do provide support for `og:image` and a card will be [automatically generated](https://dev.twitter.com/cards/markup) if an appropriate `og:type`, `og:title` and `og:description` is also provided in the header of the target page.

**Comment by sshcli** [comment]
Thanks for the information
