### ISSUE TITLE
Java - Source/target version

### ISSUE THREAD

**Issue by asgs** [twitter/twitter-text#192]
What is the intended levels of Java Source and target versions? in the [pom.xml](https://github.com/twitter/twitter-text/blob/master/java/pom.xml), the `maven-compiler-plugin` specifies a value of 1.5, while the project properties say it's 1.6.

It's better to specify the values inside the project properties.

Also, are there plans to support Java 1.8 yet? That way, we could introduce a lot of lambda sugars to the code base.

**Comment by leeaustinadams** [comment]
pom.xml is now set to hav a source and target of 1.7. 

```
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <encoding>UTF-8</encoding>
</properties>
```

It is actually redundant for us to specify them in the maven-compiler-plugin but at least they are the same value now.

We have no plans to target Java 8 at this time.
