### ISSUE TITLE
Special characters not properly counted against limit when converted to JSON

### ISSUE THREAD

**Issue by danielbonnell** [twitter/twitter-text#194]
Hello,

I noticed an issue with the JS library's `twttr.txt.getTweetLength` method. Let's say I've got the following string with a length of 140:

    var post = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero non \"volutpat\"";
    post.length
    => 140
    twttr.txt.getTweetLength(post)
    => 140

Now if I submit this as a Tweet via the API, it will be rejected because when it is converted to JSON, it is in fact 144 characters:

    JSON.stringify(post).length
    => 144
    twttr.txt.getTweetLength(JSON.stringify(post))
    => 144

I'm not sure if this is a bug with the library or just an oversight, but it's created a lot of problems for users of my app, who tend to want to use up all 140 characters. It also makes for an inconsistent UX. Hard to explain to a user who doesn't know what JSON is why some characters (e.g. `a`) count as one, while others (e.g. `"`) count as two against their limit.

**Comment by kamronbatman** [comment]
I think this can be easily fixed if the function gets the raw string?

**Comment by leeaustinadams** [comment]
Yeah, don't stringify to JSON before passing to `getTweetLength`
