### ISSUE TITLE
280 characters

### ISSUE THREAD

**Issue by v21** [twitter/twitter-text#196]
Hiya,

Now that 280 characters has rolled out to all users, can we get an update that handles this (and the special rules for what characters count double)?

Thanks,
G

**Comment by andypiper** [comment]
We [announced](https://twittercommunity.com/t/updating-the-character-limit-and-the-twitter-text-library/96425/) version 2.0 will be released shortly. For details of the new algorithm, please see the [technical documentation on the Twitter Developer site](https://developer.twitter.com/en/docs/developer-utilities/twitter-text). Thank you.

**Comment by HamletDRC** [comment]
Any update on when version 2.0  is being released?

**Comment by hebertialmeida** [comment]
While there is no official one I have implemented a version in Swift https://gist.github.com/hebertialmeida/d868bd58efe8b5240e4ef8b542107099

**Comment by andypiper** [comment]
Currently looking into mid-December before we are able to make a release due to some other moving parts.

**Comment by vitalys** [comment]
Mid-December is here. Are there any news?

**Comment by andypiper** [comment]
Just a _little_ more patience... 😉

**Comment by andypiper** [comment]
Released last Friday!
