### ISSUE TITLE
URL not being detected

### ISSUE THREAD

**Issue by linvi** [twitter/twitter-text#200]
`google.fr` is no longer being detected as a url, could you explain why and if this is a bug?

**Comment by saschanaz** [comment]
Whichever the implementation used by twitter.com does not seems to detect it as a url.

**Comment by linvi** [comment]
@saschanaz is correct. twitter.com does not detect various urls that it used to detect.

This also include `google.ca` for example.
Some of the tests used to test Tweetinvi that used no longer have the same value on twitter because of the url detection.

You can see the tests here :

https://github.com/linvi/tweetinvi/blob/master/Testinvi/Tweetinvi.Core/StringExtensionsTests.cs

Also it would be ideal on `twitter.com` to have the actual value (at least in the html even if it hidden) so that we can compare and test the length behaviour of `twitter.com` like used to be able to.

**Comment by andypiper** [comment]
Checking with the team working on twitter-text 2.0 to clarify.

**Comment by westurner** [comment]
``domain.fm`` is also failing to linkify

**Comment by codemonkey3045** [comment]
The examples here (fr, fm, ca) are all country level top level domains. When I last touched this project, urls with a CTLD required either a protocol or path to be recognized as a url. Here's a list for more: https://github.com/twitter/twitter-text/blob/138456f2fe3f93cc86b43676ea09ba1a173749c6/conformance/TldLists.java 

In the issue example google.fr doesn't work, but google.fr/ will.

**Comment by linvi** [comment]
Any update here?

**Comment by linvi** [comment]
Up?

**Comment by andypiper** [comment]
The update from @codemonkey3045 is the current status - CTLDs require a protocol or path to be parsed as URLs.

**Comment by iantheparker** [comment]
Paths don't work either. Even twitter's own "t.co" with any path appended.

**Comment by dlamacchia** [comment]
This has been addressed in commit bb953606ffd2a69fb9db0a0792ae9889eb365486.
