### ISSUE TITLE
gem breaks, asset file is a dangling symlink

### ISSUE THREAD

**Issue by duck-rh** [twitter/twitter-text#211]
Quack,

I just upgraded to 2.0 and now I've got the asset file as a symlink pointing outside the ruby dir:
lrwxrwxrwx 1 duck duck 43 Dec 18 13:49 vendor/bundle/ruby/2.3.0/gems/twitter-text-2.0.0/lib/assets/tld_lib.yml -> lib/assets/../../../conformance/tld_lib.yml

The gem is now unusable.
Could you have a look please?
\\_o<

**Comment by k1r8r0wn** [comment]
Same story here:

`/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'twitter-text'. (Bundler::GemRequireError)
Gem Load Error is: No such file or directory @ rb_sysopen - /usr/local/bundle/gems/twitter-text-2.0.0/lib/assets/tld_lib.yml
Backtrace for gem load error is:
/usr/local/lib/ruby/2.4.0/psych.rb:472:in `initialize'
/usr/local/lib/ruby/2.4.0/psych.rb:472:in `open'
/usr/local/lib/ruby/2.4.0/psych.rb:472:in `load_file'
/usr/local/bundle/gems/twitter-text-2.0.0/lib/twitter-text/regex.rb:29:in `<class:Regex>'
/usr/local/bundle/gems/twitter-text-2.0.0/lib/twitter-text/regex.rb:8:in `<module:Twitter>'
/usr/local/bundle/gems/twitter-text-2.0.0/lib/twitter-text/regex.rb:3:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/twitter-text-2.0.0/lib/twitter-text.rb:23:in `block in <top (required)>'
/usr/local/bundle/gems/twitter-text-2.0.0/lib/twitter-text.rb:22:in `each'
/usr/local/bundle/gems/twitter-text-2.0.0/lib/twitter-text.rb:22:in `<top (required)>'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `require'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
/home/dockeruser/project/config/application.rb:16:in `<top (required)>'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
/usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
/usr/local/bundle/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
        from /usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
        from /usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
        from /usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
        from /usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
        from /usr/local/bundle/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
        from /usr/local/bundle/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
        from /home/dockeruser/project/config/application.rb:16:in `<top (required)>'
        from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
        from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
        from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
        from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/bundle/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
        from /usr/local/bundle/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
        from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'`

**Comment by duck-rh** [comment]
thanks @dlamacchia
