### ISSUE TITLE
Update cocoapods for twitter-text 2.0

### ISSUE THREAD

**Issue by vitalys** [twitter/twitter-text#213]
I use `twitter-text` via cocoapods, but for now there is only version 1.14.7.
Could you update this pod to the latest version?

**Comment by dlamacchia** [comment]
Currently working on this; the way we embed IFUnicodeURL for punycode support isn't handled well by cocoapods, so I'm going to rip that out and reconfigure the project. Coming soon.

**Comment by ay8s** [comment]
Thanks for your hard work @dlamacchia. 👍

**Comment by vitalys** [comment]
Sorry for disturbing, but are there any updates? 
@dlamacchia Can I help somehow?

**Comment by dlamacchia** [comment]
Just released the 2.0.1 version of objectivec. Should be able to make progress on the cocoapod now.

**Comment by ay8s** [comment]
Thanks so much @dlamacchia. Looking forward to getting it in.

**Comment by dlamacchia** [comment]
Finally got this published -- 2.0.2 is now available for use. Please let me know if you have any issues integrating this!
