### ISSUE TITLE
[js] ReferenceError: twttr is not defined

### ISSUE THREAD

**Issue by dhritzkiv** [twitter/twitter-text#214]
This simple bit of code:

```js
const twitter = require('twitter-text');

twitter.autoLink('#hello < @world >');
```

throws a `ReferenceError`.

L557 of build/twitter-text.js references `twttr` which is not defined anywhere, except on `global.twttr`, which is `undefined` when I inspect it.

**Comment by kaushlakers** [comment]
Hey @dhritzkiv thanks for reporting! This bug was fixed in [this](https://github.com/twitter/twitter-text/pull/209) and we just released a new version. Please update to 2.0.2! Thanks!
