### ISSUE TITLE
[ruby] twitter-text-2.0.0.gem doesn't include config/v[12].json

### ISSUE THREAD

**Issue by tsutsui** [twitter/twitter-text#215]
In 2.0.0 twitter-text/blob/master/rb/lib/twitter-text/configuration.rb includes config/v1.json and config/v2.json in the top directory of the twitter-text repository
https://github.com/twitter/twitter-text/blob/34dc1dd9f10e9171100cdff0cb2b7a9ed9ea2bd6/rb/lib/twitter-text/configuration.rb#L18
https://github.com/twitter/twitter-text/tree/34dc1dd9f10e9171100cdff0cb2b7a9ed9ea2bd6/config
but they are not included in the gem file. (the gem was generated from files under rb directory?)

**Comment by dlamacchia** [comment]
Thanks for this report. We've got an update coming momentarily.

**Comment by dlamacchia** [comment]
2.0.1 has been pushed to rubygems.
