### ISSUE TITLE
NoMethodError Exception: undefined method `[]' for nil:NilClasswhen using gem in rails app

### ISSUE THREAD

**Issue by tansaku** [twitter/twitter-text#221]
We've found an odd error trying to use twitter-text in a rails app.  It works fine from the irb, and so we are a little confused.

Here's it all good in IRB:

```
[tansaku@Samuels-MBP:~/Documents/Github/AgileVentures/LocalSupport (131428629_automated_posting_to_social_media_feeds)]$ 
→ bundle exec irb
2.4.2 :001 > require 'twitter-text'
 => true 
2.4.2 :002 > include Twitter::Validation
 => Object 
2.4.2 :003 > parse_tweet "Test Tweet 4 https://www.harrowcn.org.uk/"
 => {:weighted_length=>36, :valid=>true, :permillage=>128, :valid_range_start=>0, :valid_range_end=>40, :display_range_start=>0, :display_range_end=>40} 
```

here's the full stack trace when we try to run in a test:

```
  1) TwitterApi Posting to twitter should be able to post 280 chars or less to twitter
     Failure/Error: result = parse_tweet(tweet)
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/twitter-6.2.0/lib/twitter/base.rb:128:in `attr_falsey_or_empty?'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/twitter-6.2.0/lib/twitter/base.rb:86:in `block in define_attribute_method'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
     # /Users/tansaku/.rvm/gems/ruby-2.4.2/gems/twitter-text-2.0.2/lib/twitter-text/validation.rb:41:in `parse_tweet'
     # ./app/services/twitter_api.rb:22:in `post_to_twitter'
     # ./spec/services/twitter_api_spec.rb:17:in `block (3 levels) in <top (required)>'
```

It seems like when we have the twitter gem in a rails app that this somehow interferes with the twitter-text gem - so that configuration gets looked up in the twitter gem and that breaks for some reason.  When we remove the twitter gem from the rails app then we don't get the above error.

**Comment by tansaku** [comment]
for reference here is the pull request we're working on this in: https://github.com/AgileVentures/LocalSupport/pull/463

**Comment by dlamacchia** [comment]
That's really odd. The line in question is where we fetch the scale from the config file. I wonder if it's an issue with the relative path to the config file when running inside Rails. The config file is populated in configuration.rb:23 with this:

    CONFIG_V2 = File.join(
      File.expand_path('../../../config', __FILE__), # project root
      "#{PARSER_VERSION_DEFAULT}.json"
    )

I wouldn't be surprised if that's returning an empty config inside Rails. If you log the config, is it empty?

**Comment by NickSchimek** [comment]
Hi @dlamacchia - I was working on this issue with @tansaku and when we logged the config it was not empty, but when config.scale is logged it returned the error:

```
(byebug) config
#<Twitter::Configuration:0x00007f8652d85d08 @version=2, @max_weighted_tweet_length=280, @scale=100, @default_weight=200, @transformed_url_length=23, @ranges=[#<Twitter::WeightedRange:0x00007f8652d86a78 @start=0, @end=4351, @weight=100>, #<Twitter::WeightedRange:0x00007f8652d87dd8 @start=8192, @end=8205, @weight=100>, #<Twitter::WeightedRange:0x00007f8652d8ff10 @start=8208, @end=8223, @weight=100>, #<Twitter::WeightedRange:0x00007f8652d8fe48 @start=8242, @end=8247, @weight=100>]>
(byebug) config.scale
*** NoMethodError Exception: undefined method `[]' for nil:NilClass

nil
```

**Comment by NickSchimek** [comment]
@dlamacchia @tansaku 
Update: I created a skeleton rails app to replicate the error. It is located here: https://github.com/NickSchimek/ls_twitter-text_bug

I also found a fix. It seems when we require rails-helper it is producing the error, but if we delete that and require an absolute path to the file being tested then there is no issue.

The README at the repo is fully documented on how to reproduce and fix the error.

**Comment by jeremyhaile** [comment]
We are also facing this issue in trying to upgrade to the latest twitter-text gem. It seems like it is a conflict between the twitter-text gem and the twitter gem. @NickSchimek thanks for creating a reproducible project. Has anyone found a workaround yet? If I find one, I will post here.

**Comment by jeremyhaile** [comment]
It also appears to have something to do with memoizable, which the twitter gem uses. Here is the full stack trace I'm getting when calling `parse_tweet`:

```
NoMethodError: undefined method `[]' for nil:NilClass
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/twitter-6.2.0/lib/twitter/base.rb:128:in `attr_falsey_or_empty?'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/twitter-6.2.0/lib/twitter/base.rb:86:in `block in define_attribute_method'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
/Users/jhaile/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/twitter-text-2.0.2/lib/twitter-text/validation.rb:41:in `parse_tweet'
```

And here is a stack trace I get when calling `Twitter::Configuration.default_configuration.version`:

```
NoMethodError: undefined method `[]' for nil:NilClass
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/twitter-6.2.0/lib/twitter/base.rb:128:in `attr_falsey_or_empty?'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/twitter-6.2.0/lib/twitter/base.rb:86:in `block in define_attribute_method'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
/Users/jhaile/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
/Users/jhaile/.rvm/gems/ruby-2.3.4@sideqik/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
(pry):16:in `<main>'
```

**Comment by jeremyhaile** [comment]
Ah, ok so Twitter::Configuration exists in both projects and yet is different. And in the `twitter` gem it includes Memoizable. So this is a namespace conflict. Is there any reason that `TwitterText` or `Twitter::Text` was not used as the base namespace to avoid conflicts with the `twitter` gem?

**Comment by dlamacchia** [comment]
Thanks for submitting this PR and tracking down the namespace conflict. I'll try to get an update out today (still discussing if we want to do a full namespace update or not)

**Comment by jeremyhaile** [comment]
@dlamacchia No problem. I thought `Twitter::Text::Configuration` would probably be the best name spacing, but that would also break backwards compatibility with 1.x so I'll leave that to you guys to decide =)

**Comment by dlamacchia** [comment]
Yeah...after a bit of discussion here I think we're going to change the top-level namespace to `TwitterText` so we can avoid possible conflicts in the future. Seems like the 2.x release is as good a time to do that as any (but we're going to bump the version to 2.1 due to the breaking change).

**Comment by dlamacchia** [comment]
After more discussion we decided to go with `Twitter::TwitterText` (which also happens to be similar to what Java does). I've updated master and pushed the 2.1 gem to rubygems.

**Comment by NickSchimek** [comment]
@jeremyhaile @dlamacchia Thank you for all your work! 😃

**Comment by abdullaachilov** [comment]
Hello, everyone, I think I have similiar issue, but just with twitter gem. It works in rails c, but doesn't in lib/

     undefined method `each_byte' for nil:NilClass

in a row

      twitter_client.update(tweet_text.to_s)
      def twitter_client
        Twitter::REST::Client.new do |config|
          config.consumer_key = credentials[:consumer_key]
          config.consumer_secret = credentials[:consumer_secret]
          config.access_token = credentials[:access_token]
          config.access_token_secret = credentials[:access_token_secret]
          config.user_agent = "TwitterRubyGem/6.2.0"
        end
      end
