### ISSUE TITLE
js parseTweet breaks on 2-letter tld

### ISSUE THREAD

**Issue by iantheparker** [twitter/twitter-text#226]
```
message = "Let's get humans living on #mars t.co";
twttr.txt.parseTweet(message);
```
Same results if I add a path or a scheme to the url ( t.co/poo or http://t.co/poo). 

Yields this error **every other time** entered in the console.

Uncaught TypeError: Cannot read property 'toASCII' of undefined at Object.toAscii 
` 
var punycodeEncodedLabel = punycode.toASCII(label);
`

Edit: Just realized that these are all the same issue. Adding a path (as @codemonkey3045  has suggested) or a scheme doesn't help.
https://github.com/twitter/twitter-text/issues/200
https://github.com/twitter/twitter-text/issues/171
https://github.com/twitter/twitter-text/issues/153

**Comment by kaushlakers** [comment]
@iantheparker have you updated to the latest version? Are you using 2.0.2 ?

**Comment by iantheparker** [comment]
@kaushlakers  Yup, I'm on 2.0.2. Were you able to replicate?

**Comment by kaushlakers** [comment]
@iantheparker Can you share a gist?

I ran the same query on runkit here and it seems to work: https://runkit.com/kaushlakers/5a4eaa1c68ee540012d16807

**Comment by iantheparker** [comment]
I tried your runkit and it was fine, but here's how you can repro locally.

1. I installed v2.0.2 via yarn
2. included the single file 'build/twitter-text.js' in the head of some new html file.
3. Open the file in Chrome and start playing with the console.I recommend entering in each line twice, because you'll notice that half the 't.co' break, and half the time they don't.

Here's what I'm seeing
```
twttr.txt.parseTweet("t.com");
-> {weightedLength: 5, valid: true, permillage: 17, validRangeStart: 0, validRangeEnd: 4, …}
twttr.txt.parseTweet("t.com");
-> {weightedLength: 5, valid: true, permillage: 17, validRangeStart: 0, validRangeEnd: 4, …}
twttr.txt.parseTweet("t.co");
-> Uncaught TypeError: Cannot read property 'toASCII' of undefined
twttr.txt.parseTweet("t.co");
-> {weightedLength: 4, valid: true, permillage: 14, validRangeStart: 0, validRangeEnd: 3, …}
```

Now try opening in Safari. It breaks on 3-letter tlds as well as 2. Other strings are fine.

```
twttr.txt.parseTweet("let's live on mars");
-> {weightedLength: 18, valid: true, permillage: 64, validRangeStart: 0, validRangeEnd: 17, …}
twttr.txt.parseTweet("let's live on mars");
-> {weightedLength: 18, valid: true, permillage: 64, validRangeStart: 0, validRangeEnd: 17, …}
twttr.txt.parseTweet("t.com");
-> {weightedLength: 5, valid: true, permillage: 17, validRangeStart: 0, validRangeEnd: 4, …}
twttr.txt.parseTweet("t.com");
->**TypeError: undefined is not an object (evaluating 'punycode.toASCII')**
twttr.txt.parseTweet("t.co");
-> {weightedLength: 4, valid: true, permillage: 14, validRangeStart: 0, validRangeEnd: 3, …}
twttr.txt.parseTweet("t.co");
->TypeError: undefined is not an object (evaluating 'punycode.toASCII')
```

**Comment by kaushlakers** [comment]
@iantheparker if you install via npm/yarn you cannot directly include the file that way. This is because twitter-text has an explicit dependency on punycode i.e. when you use `require('twitter-text')` in javascript, a module bundler like [webpack](https://webpack.js.org/) or [rollup](https://github.com/rollup/rollup) will resolve it for you. 

If you need a standalone version of twitter-text to include in an html file,  you can do use the one we provide in the pkg folder here: https://github.com/twitter/twitter-text/blob/master/js/pkg/twitter-text-2.0.2.js

That has punycode bundled into it.

**Comment by iantheparker** [comment]
Touché! @kaushlakers Are you guys against there being a dist directory from the npm install for accessing the most recent fully-baked version?

**Comment by jmchaves** [comment]
In my case I fixed the issue using:

`yarn add punycode`

Then:

`yarn upgrade twitter-text@2.0.3`

Finally: 

`yarn install`
