### ISSUE TITLE
GetTweetLength returns wrong value

### ISSUE THREAD

**Issue by leventeolahx** [twitter/twitter-text#227]
Hi,

When the tweet contains emoji the method doesn't work properly. 

Normal emoji: 🎉 😍 (should be 2 characters each one)
Emoji with skin tone: 💪🏻 (should be 4 characters)

I had similar issue in C#, there the problem was that i used UTF32Lengtgh for calculating the tweet length. Maybe it's similar the problem here too.

Cheers,
Olah Levente

**Comment by kaushlakers** [comment]
@leventeolahx what is the version of twitter-text you are using? Also is this for js, objC, ruby or Java?

**Comment by leventeolahx** [comment]
@kaushlakers i'm using v1.14.7 in javascript

**Comment by clementEchobox** [comment]
Following @kaushlakers' recommendation in  https://github.com/twitter/twitter-text/issues/203 I am using the latest version V2.0.9 for Java but  the problem with emojis remains.
this emoji :  ⛄️  is counted a 4 on twitter, but  twitter-text counts it as 2, 🏳️‍🌈 is counted as 7 by twitter, but 4 by twitter-text. 
There are also difference depending on whether you introduce the emoji via the box or paste it in the tweet from elsewhere, but in this case even the twitter box is not consistent.

**Comment by andypiper** [comment]
Have you tried using 2.0.2 and using the new parseTweet function? GetTweetLength is now deprecated.

```
console.log(twitter.parseTweet("🎉😍"))
{ weightedLength: 4,
  valid: true,
  permillage: 14,
  validRangeStart: 0,
  validRangeEnd: 3,
  displayRangeStart: 0,
  displayRangeEnd: 3 }
```

```
console.log(twitter.parseTweet("💪🏻"))

{ weightedLength: 4,
  valid: true,
  permillage: 14,
  validRangeStart: 0,
  validRangeEnd: 3,
  displayRangeStart: 0,
  displayRangeEnd: 3 }
```

**Comment by kaushlakers** [comment]
Closing this as there's been no update. @leventeolahx issue should be fixed with latest version.
