### ISSUE TITLE
Find a lightweight alternative for the fasterxml dependency in Java

### ISSUE THREAD

**Issue by DMAPro** [twitter/twitter-text#232]
Hello,

The Java version of TwitterText depends on `com.fasterxml.jackson`. This is a huge dependency, and it is only used to parse a single static 30-line JSON file.
This single library contains ~5500 method references. Our whole Twitter client app (without dependencies) contains about 7000. The reason it's bad is that Android has a method references number threshold of 64K. If you go above it, your app has to work in Multidex mode, which has performance penalties.
Having such a big dependency for such a simple task looks very unoptimal.

Please, consider changing it to something more lightweight.

Thanks.

**Comment by denisk20** [comment]
Please consider fixing it. Version 2.x is currently unusable on Android for us.

**Comment by denisk20** [comment]
I have created a pull request to use Gson instead of Jackson, it saves 9000+ methods, please take a look
https://github.com/twitter/twitter-text/pull/241

**Comment by leeaustinadams** [comment]
Working on preparing a push to github that removes the dependency entirely.

**Comment by leeaustinadams** [comment]
#310 fixes this by removing JSON data files and Jackson dependency entirely (except for tests)
