### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by jenzz** [twitter/twitter-text#24]
Using the latest Java library `com.twitter:twitter-text:1.11.0` I'm getting the following crash when calling `new Extractor().extractEntitiesWithIndices(tweet)`.

```
java.lang.ExceptionInInitializerError
    at com.twitter.Extractor.extractURLsWithIndices(Extractor.java:297)
    at com.twitter.Extractor.extractEntitiesWithIndices(Extractor.java:156)
```

Line 297: `Matcher matcher = Regex.VALID_URL.matcher(text);`

So there might be an issue compiling the URL regex pattern?
The exception is not thrown when using the old `1.9.9` version.

**Comment by virengujariya** [comment]
I am facing the issue with latest version ```1.13.4```

**Comment by turco082** [comment]
Someone might resolve this error?

**Comment by leeaustinadams** [comment]
Fixed in latest
