### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'domain.startsWith('xn--')')

### ISSUE THREAD

**Issue by rcastera** [twitter/twitter-text#245]
I'm testing the `parseTweet` method by passing a URL and I'm getting a type error:

## Test:
```
var message = 'http://www.cnn.com';
var result = twttr.txt.parseTweet(message);
```

## Error:
```TypeError: undefined is not a function (evaluating 'domain.startsWith('xn--')') in /bower_components/twitter-text/js/pkg/twitter-text-2.0.2.js (line 843)```

**Comment by kaushlakers** [comment]
Hi @rcastera. So sorry for the delayed response. Actually this issue was fixed in this PR: https://github.com/twitter/twitter-text/pull/244

Looks like I forgot to publish a standalone version in pkg. Let me just do that now.

**Comment by kaushlakers** [comment]
Standalone version is here: https://github.com/twitter/twitter-text/blob/master/js/pkg/twitter-text-2.0.3.js 

Plz test and let me know if this is fixed! Again so sorry for the delayed response!

**Comment by rcastera** [comment]
@kaushlakers no worries. That's great! Will give it a shot.

Also I noticed that the tag v2.0.3 is missing the updated version of v2.0.3 in pkg: https://github.com/twitter/twitter-text/tree/v2.0.3/js/pkg
