### ISSUE TITLE
/pkg folder

### ISSUE THREAD

**Issue by roderickhsiao** [twitter/twitter-text#25]
Greeting,

Thanks for developing the package, its really useful.

wondering do we need to pack the file under /pkg to ``npm`` when building the package? as we are archiving all the version js, the npm package is actually quite large but we are not directly using files under the folder. or just keep the current file in that package version will be great.

@hankhsiao

**Comment by jakl** [comment]
I added pkg/ to .npmignore
The published npm packages should be tiny now.

**Comment by roderickhsiao** [comment]
thanks @jakl
