### ISSUE TITLE
Way of creating and overriding the default config not documented

### ISSUE THREAD

**Issue by juanlet** [twitter/twitter-text#259]
I need to work with spanish instead of english to know the remaning characters left, how do I do that?. SInce I see it comes in English by default, and it mentions a configuration file but it doesn't say anything in the docs. Where can I find how to override this?

**Comment by andypiper** [comment]
There's no difference between English and Spanish in terms of how characters are counted. twitter-text 2 (i.e. the version for 280) uses configVersion2 by default.

**Comment by juanlet** [comment]
Thanks my friend, so, I can use the weightedLength field from parseTweet without any problem to know how many characters were used by a certain string or is there a better way?

**Comment by dlamacchia** [comment]
That's exactly right, reference the weightedLength field for this purpose.
