### ISSUE TITLE
Asterisk character (*) counted incorrectly by JS library

### ISSUE THREAD

**Issue by summera** [twitter/twitter-text#269]
One line summary of the issue here.

### Expected behavior

Asterisk should be counted correctly in text to match the Twitter API, which considers it as two characters.

### Actual behavior

Library counts asterisk as a single character.

### Steps to reproduce the behavior

The following is counted as 280 characters by the library:
> sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss*

Publishing a Tweet with the above text will fail and Twitter complains that the Tweet is too long. When replacing "*" with a period it will publish successfully.

**Comment by kaushlakers** [comment]
@summera I'm pretty sure Asterisk is counted as 1 character. And I was able to create the following Tweet:
https://mobile.twitter.com/notmyac62238089/status/1053432935850795008

**Comment by andypiper** [comment]
I've been unable to reproduce this report running twitter-kit 3.0.0 on Runkit on npmjs, with that same string. Returns `weightedLength` of 280, and valid.

**Comment by summera** [comment]
@kaushlakers @andypiper Thanks for taking a look. I should have been more specific in my explanation above. Everything does work correctly when posting that sample string through the web UI. The problem is in the Twitter API. When attempting to post the above sample string via the Twitter API, for some very weird reason Twitter throws a "Could not authenticate you" error.  You can verify this with `twurl`:

```sh
❯❯❯ twurl -d 'status=sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss*' /1.1/statuses/update.json
{"errors":[{"code":32,"message":"Could not authenticate you."}]}
```

In order to fix that error we ended up subbing out the asterisk for the small asterisk character (U+FE61) when posting statuses which actually does count as two characters for the `weightedLength`. I forgot we had done this so I incorrectly assumed the regular asterisk was the issue here. So it seems that the javascript library here is not the issue and the real issue lies in the fact that the Twitter API incorrectly returns "Could not authenticate you" for a perfectly valid status. 

I apologize for the confusion. This issue is also described here  - https://twittercommunity.com/t/asterisk-not-allowed-in-status-update/56097/5. I'm surprised it's still an issue as this was reported in 2015!

**Comment by andypiper** [comment]
I'm almost certain that this is related to incorrect character encoding in the OAuth string in that case. I'll dig some more when I have some time.

**Comment by summera** [comment]
> I'm almost certain that this is related to incorrect character encoding in the OAuth string in that case. I'll dig some more when I have some time. Weird that twurl is failing too.

That would be great. Thanks! I'm seeing the same issue with the [Twitter gem](https://github.com/sferik/twitter), so it's not just twurl.

**Comment by summera** [comment]
@andypiper looks like you may be right about this being a character encoding issue - https://github.com/sferik/twitter/issues/677#issuecomment-400226041
