### ISSUE TITLE
Java: 3.0.1 crashes with NPE when proguard is used

### ISSUE THREAD

**Issue by yshrsmz** [twitter/twitter-text#270]
On Android, `TwitterTextParser.parseText(String)` crashes with NPE if proguard is used.

### Expected behavior

Should return valid `TwitterTextParseResults` as usual.

### Actual behavior

Crashes with NPE. `TwitterTextParser.parseText(String, TwitterTextConfiguration)` also crashes.

Below is the crashlog

```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.twitter.a.h.a(TwitterTextParser.java:173)
        at com.twitter.a.h.a(TwitterTextParser.java:78)
        at net.yslibrary.omnitweety.status.a.c.f(BuildStatusString.kt:35)
        at net.yslibrary.omnitweety.status.a.c.a(BuildStatusString.kt:11)
        at net.yslibrary.omnitweety.status.a.c$a.agp(BuildStatusString.kt:16)
        at net.yslibrary.omnitweety.status.a.c$a.call(BuildStatusString.kt:11)
```

Here's the code in above crashlog.

```kotlin
private fun getLengthDiff(status: String): Int {
    val result = TwitterTextParser.parseTweet(status)
    return TwitterTextParser.TWITTER_TEXT_WEIGHTED_CHAR_COUNT_CONFIG.maxWeightedTweetLength - result.weightedLength
}
```

### Steps to reproduce the behavior

1. Create android app
2. Enable proguard(also add proguard config for Jackson)
3. Call `TwitterTextParser.parseTweet(String)` somewhere

**Comment by yshrsmz** [comment]
looks like additional proguard config below solved the problem for now.

```
-keep class com.twitter.twittertext.TwitterTextConfiguration { *; }
```

**Comment by leeaustinadams** [comment]
Assigned to me and I'll add Android specific portions to the README and we're evaluating options related to configuration in general for some other issues filed.

**Comment by leeaustinadams** [comment]
I've got a patch internally that packages the necessary proguard rules within the JAR itself. I will update the README. Still working towards a push to GitHub, stay tuned.

**Comment by leeaustinadams** [comment]
Hoping to push back to github in the near future!

**Comment by leeaustinadams** [comment]
#310 release fixes by removing the JSON data files entirely
