### ISSUE TITLE
Domains and emails with non-ASCII characters are not hyperlinked

### ISSUE THREAD

**Issue by UA2018** [twitter/twitter-text#273]
Email Address Internationalization (EAI) is not hyperlinked correctly.

Here is the link to the tweet: https://twitter.com/datamail_in/status/1055140179089022976?s=19

The email address with non-ASCII character in the above tweet is valid and expected to have a hyperlink when typed in twitter application.

A quick guide that explains the expected behavior of a correct linkification is here: 
https://uasg.tech/wp-content/uploads/2017/06/UASG010-Quick-Guide-to-Linkification.pdf

It only linkifies until it comes across "á" letter. There is no link below "á" character. 

Internationalized Domain Names (IDNs) permit the global community to use a domain name in their native language or script. This is enabled by allowing domain names to have characters from different scripts, beyond the letters (a to z), digits (0 to 9) and hyphen (-), as encoded by the Unicode standard and as allowed by relevant IDN protocols.

Email Address Internationalization (EAI) is the protocol that allows email addresses with IDNs in the domain part and/or Unicode (non-ASCII) characters in the Local part of the Mailbox name.  Please see the quick guide for EAI from here:
https://uasg.tech/wp-content/uploads/2017/02/UASG014_20170206.pdf

Kindly please look into this issue.

Thank you in advance.

**Comment by UA2018** [comment]
Hi, 
Are there any updates on this issue? 
I was wondering how long it can take to assign the case to someone?
Thank you

**Comment by leeaustinadams** [comment]
We shouldn't have identified that portion of the text as a link at all. It is not a goal of twitter-text to identify email addresses. This is a bug, but the fix will be to prevent detecting a url incorrectly at all.

**Comment by UA2018** [comment]
Dear leeaustinadams, 

Thank you for your reply. I am happy to hear an update.

Let me provide you with more clarification. Universal Acceptance is a concept of treating all domain names equally. If twitter recognizes email addresses or domain names on a tweet, and linkifies, we expect this to happen for all email addresses and domain names, including the ones that have non-ASCII characters. Non-ASCII email holders, domain holders, as Twitter users, will experience dissatisfaction if no action is taken.

To excel in the long run, organizations need to ensure their systems work with the naming infrastructure of the Internet –the domain name system. When businesses are UA-ready, their systems and services will work with the continuously expanding domain name space. It also helps businesses set themselves
up for future opportunities and success by supporting their customers using their customers’ chosen identities.

UA-ready websites, applications and services lead to better user experiences. When a company is UA-ready, email addresses in any script from any domain name can be used. When a site is UA-ready, it will allow customers with domain names in new top-level domains to successfully use the site and its forms.

For this reason, we would appreciate if you can look into this issue. I am including some reference materials for you and your team to review:

Linkification : https://uasg.tech/wp-content/uploads/2017/06/UASG010-Quick-Guide-to-Linkification.pdf
Fact Sheet : https://uasg.tech/wp-content/uploads/2016/08/UASG003-160823-en-onesheet-digital.pdf
All Resources : https://uasg.tech/documents/

Please let me know if you have any questions. Looking forward to hearing positive updates from you.
Have a great day!

**Comment by leeaustinadams** [comment]
Noted, thank you for your thoroughness. We shouldn't have recognized that as a domain because it was an email address and we do not want to hyperlink email addresses.

**Comment by UA2018** [comment]
Hello,
I was wondering if this case will be assigned to someone?
Looking forward to hearing from you about my 2nd question on domain name senton Dec 6 2018 above.
Best regards.

**Comment by leeaustinadams** [comment]
Assigned to me, have internal review underway. Thanks for your patience!

**Comment by UA2018** [comment]
Hi Leeautinadams,

Thank you for the update.
May I also ask you to reopen our case based on the additional information we add on https://github.com/twitter/twitter-text/issues/281 

Thanks in advance.

**Comment by leeaustinadams** [comment]
I will try and see if there is a relationship between this code and #281 or if that represents some kind of policy decision (which I can make no promises about).
