### ISSUE TITLE
We cannot create a twitter account

### ISSUE THREAD

**Issue by UA2018** [twitter/twitter-text#281]
We cannot create twitter accounts with the email addresses ending with
[....@nudge.solutions](mailto:....@nudge.solutions)
[....@nudge.services](mailto:....@nudge.services)

the parts before the @ sign consist of ASCII characters. However, it is not possible to create an account with TLDs .services or .solutions.

Can you please help?

**Comment by UA2018** [comment]
We cannot create twitter accounts with the email addresses ending with 
....@nudge.solutions 
....@nudge.services 

the parts before the @ sign consist of ASCII characters. However, it is not possible to create an account with TLDs .services or .solutions.

Can you please help?

**Comment by leeaustinadams** [comment]
Twitter text is not involved in validating email addresses during account creation, afaik. Have you tried @TwitterSupport?

**Comment by UA2018** [comment]
Hi again,

We found a related post on twitter community relating to new gTLDs, such as . technology.

This post is referring to the Github twitter-text.
Please see the details here:
https://twittercommunity.com/t/creating-an-application-for-a-technology-url/14472/2
https://github.com/twitter/twitter-text/blob/master/conformance/tld_lib.yml

When I try to create an account with  .technology, .services and .consulting email addresses on https://twitter.com/i/flow/signup , I still get an error as "Please enter a valid email."

When we first raised such issues, I was directed by Twitter Developer Forum to Github.
https://twittercommunity.com/t/domains-and-emails-with-non-ascii-characters-are-not-linkified/116301

I truly appreciate if you can provide assistance on this issue.

Best regards,
Seda

**Comment by leeaustinadams** [comment]
This definitely is not due to twitter-text, however, we have identified some arbitrary limits that are the probably cause of your inability to register with those gTLDs. Fixes for the various clients should be slowly making their way to production.
