### ISSUE TITLE
Cannot create an account on Twitter with New gTLDs and in UTF-8

### ISSUE THREAD

**Issue by UA2018** [twitter/twitter-text#282]
We expect that all top level domains are treated equally.

In actual fact, we cannot create Twitter accounts with the email addresses that are ending usually more than 4 characters or that are including UTF-8 (non-ASCII characters).
Examples to the email addresses that are not recognized by Twitter are:
info2@ua-test.technology
uatest@@ddms.consulting 
测试1@ua-test.link

I get an error as "Please enter a valid email on https://twitter.com/i/flow/signup ,
when trying to create accounts with the above-mentioned email addresses.

However, email addresses that are ending with .charity or .sport are accepted on Twitter.

We also found a related post on twitter community relating to new gTLDs, such as . technology.
This post is referring to the Github twitter-text. Please see the details here:
https://twittercommunity.com/t/creating-an-application-for-a-technology-url/14472/2
https://github.com/twitter/twitter-text/blob/master/conformance/tld_lib.yml

While .charity is accepted, .technology or .consulting emails are not recognized. 
(To see all valid TLDs, visit https://www.icann.org/resources/pages/tlds-2012-02-25-en )

Your rapid action on this issue is highly appreciated.

**Comment by leeaustinadams** [comment]
Have confirmed that twitter-text is not involved in validating, accepting, nor rejecting email addresses during account signup or account changes. I have raised the issue internally with the right groups and they will decide from there the appropriate changes, if any. Thanks for reporting!
