### ISSUE TITLE
How to update to latest version of twiter-text since npm is giving error No matching version found for twitter-text taking 1.14.3 as latest one where as git hub docs shows it as 3.0.1

### ISSUE THREAD

**Issue by jayaramasaipavanmanda** [twitter/twitter-text#293]
One line summary of the issue here.

### Expected behavior

As concisely as possible, describe the expected behavior.

### Actual behavior

As concisely as possible, describe the observed behavior.

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

**Comment by jayaramasaipavanmanda** [comment]
I am currently trying to update character count which is getting calculated wrongly.

**Comment by kaushlakers** [comment]
Should be fixed now, sorry for the trouble! 3.0.1 should be available.

**Comment by jayaramasaipavanmanda** [comment]
@kaushlakers Its still installing twitter-text@1.14.3 when I use this command npm i twitter-text after deleting previous old modules.Could you please look into this.

**Comment by kaushlakers** [comment]
Are you saying it's not updating the package.json or that it's not installing itself? If you meant updating the package file, I think you are missing the `--save` flag i.e `npm i twitter-text --save`. 

If it's not installing the modules itself, then I'm not sure what is causing the issue. I'm unfortunately not able to repro and this isn't a `twitter-text` library issue.

**Comment by jayaramasaipavanmanda** [comment]
@kaushlakers Since getTweetLength is giving wrong value and is getting deprecated , I am trying to use parseTweet which is currently not available in my @types/twitter-text file. I am trying to update to use parseTweet and I am getting same version installed.
