### ISSUE TITLE
Update documentation - specifically for CJK and Emoji

### ISSUE THREAD

**Issue by edent** [twitter/twitter-text#303]
The official documentation doesn't reflect reality. Especially around Chinese, Japanese, and Korean text.

On https://developer.twitter.com/en/docs/basics/counting-characters the documentation says

> Tweet length is measured by the number of codepoints in the NFC normalized version of the text.

This is not *quite* true :-)

The Twitter-Text page - https://developer.twitter.com/en/docs/developer-utilities/twitter-text - says:

> The Configuration defines Unicode code point ranges, with a weight associated with each of these ranges. **This enables language density to be taken into consideration when counting characters.**

But it doesn't explain which high-density languages are included.  Nor does it explain Emoji.

## Reading between the lines

On [the blog post announcing 280 characters](https://blog.twitter.com/en_us/topics/product/2017/Giving-you-more-characters-to-express-yourself.html), you say:

> We want every person around the world to easily express themselves on Twitter, so we're doing something new: we're going to try out a longer limit, 280 characters, in languages impacted by cramming (**which is all except Japanese, Chinese, and Korean**).

Hidden in the [POST status/update](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update) documentation, it says:

> To make room for more expression, we will now count all emojis as equal—including those with gender‍‍‍ ‍‍and skin tone modifiers 👍🏻👍🏽👍🏿. This is now reflected in Twitter-Text, our Open Source library.

But I don't see that in the official documentation anywhere.

## Suggestion

* Update both https://developer.twitter.com/en/docs/basics/counting-characters and https://developer.twitter.com/en/docs/developer-utilities/twitter-text 
* Explain how emoji are counted
* Explain that CJK text is still restricted to 140 characters
* If possible, give a simple explanation of the weightedLength algorithm for mixed content.

**Comment by andypiper** [comment]
Thanks, this has been on our (my) backlog for a while - thus the line in the counting chars page about the documentation to be updated soon (!!) ... sorry about that! This is good feedback. I'll move it up my list for attention.

**Comment by andypiper** [comment]
Thanks for the feedback! Happy to say that the counting characters page has now been completely overhauled, we appreciate your support!

https://developer.twitter.com/en/docs/basics/counting-characters

(the twitter-text page on the dev site will follow in the future)
