### ISSUE TITLE
.gay TLD is missing from https://github.com/twitter/twitter-text/blob/master/conformance/tld_lib.yml  

### ISSUE THREAD

**Issue by UA2018** [twitter/twitter-text#305]
.gay TLD is missing from https://github.com/twitter/twitter-text/blob/master/conformance/tld_lib.yml

As the library seems to be used for Twitter, domains like example.gay are not recognized there.

Please update the TLD listing listing as quickly as possible or automate the update by drawing the content from the DNS root zone or from https://www.iana.org/domains/root/db

Regards

**Comment by dlamacchia** [comment]
This will be addressed by https://github.com/twitter/twitter-text/pull/308
