### ISSUE TITLE
Regex incorrectly when string  is "#happy6⃣6⃣6⃣" OC

### ISSUE THREAD

**Issue by ziyingjing** [twitter/twitter-text#312]
when string like  "#6⃣",regex return length incorrectly, As shown

![7016EAB1706FD05AEB1147901A6F6743](https://user-images.githubusercontent.com/8833911/78783079-a1563d80-79d5-11ea-9c8b-ba5926ff7458.jpg)

**Comment by andypiper** [comment]
Just to be completely clear, this is in the Objective-C class and with that specific string (with how many emoji please?)

**Comment by ziyingjing** [comment]
Yes , this is in the Objective-C class , the  specific string when containing emoji numbers （like 6⃣ or 9️⃣),  when I call "hashtagsInText" method，length is incorrect, you can use （#happy6⃣ or #happy6⃣6⃣）to try，Thanks

**Comment by ziyingjing** [comment]
sorry,It is our code caused this bug
