### ISSUE TITLE
Missing docs?

### ISSUE THREAD

**Issue by transitive-bullshit** [twitter/twitter-text#319]
Several previous issues like #303 reference docs like https://developer.twitter.com/en/docs/developer-utilities/twitter-text which seems to no longer exist.

Searching the twitter developer docs for "twitter-text" yields no results and the list of [official twitter libraries](https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries) no longer mentions twitter-text.

Which leads me to a few questions:

1. Where can we go to view basic documentation for these packages aside from reading through the source code? I'm specifically interested in the JS library.
2. Is this library still actively maintained by Twitter?
3. If I have a `tweet` object from the Twitter API, what's the best way in JS to manage it with convenience methods?

Thanks!

**Comment by andypiper** [comment]
Thanks for raising this. As part of resolving issue #303, we took down the page on the developer website, as the content was being duplicated between that page, the README for the library, and the [Counting Characters](https://developer.twitter.com/en/docs/basics/counting-characters) page (which now is in much better shape in terms of describing the way this library handles counting).

You're right that `twitter-text` therefore lost its prominence on the developer site, and we need to work on fixing that. The Counting Characters page does point at this repository, but I think that may be the only reference to it.

Answers for you:

1. Each of the relevant packages should be published to their respective package managers ([npmjs](https://www.npmjs.com/package/twitter-text) in the case of the JS code) and documented there and in the local readmes here on GitHub. 

2. Yes, this library is maintained, and we do our best to keep any internal changes in sync with GitHub. Sometimes there are some delays, related to using slightly different review and CI tooling etc internally.

3. "It depends" - on what you want to do.

For example, I have a Gist [here](https://gist.githubusercontent.com/andypiper/32bdb4c7f0b8d65385fc7c8fa3988083/raw/c56cb2665938681348f25f7b56f39efef397798a/validate-tweet.js) that takes a Tweet's text and then validates and tokenizes it using the JS library. 

Note that `twitter-text` is *all* about tokenizing the text content of a Tweet - it does nothing special with anything else you'll find in a Tweet JSON object.
