### ISSUE TITLE
@ on mention is outside the anchor tag

### ISSUE THREAD

**Issue by framelita** [twitter/twitter-text#350]
**Describe the bug**
When running autoLink, mention's @ sign is outside the anchor tag

**To Reproduce**
`twitter.autoLink('@TwitterSpaces')`

**Expected behavior**
Currently it's returning:
`@<a class="tweet-url username" href="https://twitter.com/TwitterSpaces" data-screen-name="TwitterSpaces" rel="nofollow">TwitterSpaces</a>`
When it's supposed to be:
`<a class="tweet-url username" href="https://twitter.com/TwitterSpaces" data-screen-name="TwitterSpaces" rel="nofollow">@TwitterSpaces</a>`

Example on Twitter page:
![image](https://user-images.githubusercontent.com/5145692/124924533-217eaf00-e02e-11eb-99af-6887be9e0b07.png)
![image](https://user-images.githubusercontent.com/5145692/124924634-3b1ff680-e02e-11eb-9f29-945668e5c518.png)

**Comment by stratgt10** [comment]
Nice

**Comment by stratgt10** [comment]
Nice

**Comment by geekysrm** [comment]
Hey, I found myself scratching my head with this and found the answer on one of the closed issues.

Use this:
`twttr.txt.autoLink('foo test @foo',  { usernameIncludeSymbol: true } );`

**Comment by jamauro** [comment]
Thanks @geekysrm!

**Comment by framelita** [comment]
Thanks @geekysrm!
