### ISSUE TITLE
Emojis in URLs

### ISSUE THREAD

**Issue by andypiper** [twitter/twitter-text#36]
Context - Coke started a campaign with emojis in URLs. They are not hyperlinked in Twitter apps.
http://mashable.com/2015/02/20/coke-emoji-web-addresses/

Whether or not they should be clickable, is debatable?
http://www.washingtonpost.com/news/the-intersect/wp/2015/02/23/the-surprisingly-complex-reason-you-never-see-emoji-urls/

There certainly are some gTLDs that support this format of URL but they are not common.

**Comment by edent** [comment]
In addition, it's possible to put Emoji in the PATH of a URL.  For example `http://bit.ly/😀` ought to be seen as `http://bit.ly/%F0%9F%98%80`

This currently doesn't work on Twitter - see https://twitter.com/edent/status/581398954123886592

It does work on GitHub - http://bit.ly/😀

I would contend that Emoji are no different to other non-ASCII characters. For example, I run https://莎士比亚.org/奥瑟罗 - to say that URL shouldn't be clickable is, I think, a mistake.
