### ISSUE TITLE
Add all valid .tld

### ISSUE THREAD

**Issue by edent** [twitter/twitter-text#44]
Issue: Currently, Twitter will auto-link a URL like example.zip but will *not* auto-link www.bbc

Proof: https://twitter.com/edent/status/581394369804136450

Solution: The latest TLDs from http://data.iana.org/TLD/tlds-alpha-by-domain.txt should be added to https://github.com/twitter/twitter-text/blob/master/conformance/tld_lib.yml and https://github.com/twitter/twitter-text/blob/master/conformance/tlds.yml

**Comment by jakl** [comment]
Included in #55 thanks
