### ISSUE TITLE
include conformance directory inside gem

### ISSUE THREAD

**Issue by pravi** [twitter/twitter-text#45]
currently the tests fail because it can't find conformance files inside test folder

**Comment by nicol-699** [comment]
/var/mobile/Containers/Data/Application/49D22585-E2A6-4794-9AA0-07D9E61FCCB7/Documents/101361125395531365342/0B5VVdxBPEokYVlRFdERBLXk5TlE/tbslog.txt

**Comment by codemonkey3045** [comment]
Closing old ticket. There's no tests currently failing.
