### ISSUE TITLE
auto-linking example not match twitter api

### ISSUE THREAD

**Issue by hurelhuyag** [twitter/twitter-text#47]
twitter api result:
![screenshot from 2015-04-02 19 12 33](https://cloud.githubusercontent.com/assets/1059242/6962100/f3ba8300-d963-11e4-9598-680549b35f1b.png)
this project's provided example:
![screenshot from 2015-04-02 19 12 52](https://cloud.githubusercontent.com/assets/1059242/6962112/0aeab54a-d964-11e4-918e-6ae4a5d8d2dc.png)

**Comment by codemonkey3045** [comment]
Closing old tickets. Please add more details and/or open pull request.
