### ISSUE TITLE
mvn release:perform javadoc plexus stringutils error

### ISSUE THREAD

**Issue by jakl** [twitter/twitter-text#56]
I wasn't able to include the javadocs in the 1.12.0 release because of this error. I tried updating all plugin versions to their latest, and adding javadoc failOnError=false to the pom. Nothing seemed to fix it. This should be looked at later by someone familiar with maven and pom files.

mvn javadoc:javadoc  # this javadoc generation is one step that's part of mvn release:perform
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project twitter-text: Execution attach-javado
cs of goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar failed: An API incompatibility was encountered while executing org.apache.maven.plugins:ma
ven-javadoc-plugin:2.10.3:jar: java.lang.NoSuchMethodError: org.codehaus.plexus.util.StringUtils.unifyLineSeparators(Ljava/lang/String;)Ljava/lang/String;

**Comment by jakl** [comment]
I released v1.12.0
Maybe someone could verify the javadocs work for them, and reply here.

**Comment by jakubmarton** [comment]
Sources have been downloaded OK for me.
