### ISSUE TITLE
RTL hashtag support?

### ISSUE THREAD

**Issue by lukecarbis** [twitter/twitter-text#58]
Suppose I leave a comment with hashtags like this: #door #porte #porta דלת#.

This is an interesting edge case. The hash tag should be at the beginning of the word, so with the Hebrew word (read Right To Left) the hashtag is technically in the correct position. 

However, adding a hash to the right of the RTL word doesn't parse as a hashtag. 

Should it?

**Comment by codemonkey3045** [comment]
This is an odd edge case where we're mixing RTL and LTR. We won't be fixing this for now, but will revisit if need be.
