### ISSUE TITLE
twitter-text/rb/lib/twitter-text/rewriter.rb was changed 5 months ago and pulled into 1.12.0 and has a bug in it

### ISSUE THREAD

**Issue by steve-rodriguez** [twitter/twitter-text#69]
Twitter::Rewriter.rewrite_entities was changed on 1/10/2015.   This line of code, indices = entity.respond_to?(:indices) ? entity.indices : entity[:indices] does not work as intended  ( on line 9 and line 15 ).   The respond_to? command returns true on the entity which is a hash, but entity.indices return an EMPTY array. SO line 16 blows up with a 'bad range' error.   I reverted to version 1.11.0 of this gem for the time being.   Please fix.  Thx.

**Comment by dlamacchia** [comment]
Investigated this old issue and in the current version (under ruby 2.5) entity.respond_to?(:indices) returns false for a simple Hash.
