### ISSUE TITLE
big npm package size cause of 520 MB file inside

### ISSUE THREAD

**Issue by silentroach** [twitter/twitter-text#79]
Here is fresh twitter-text package - https://registry.npmjs.org/twitter-text/-/twitter-text-1.13.0.tgz
Size = **184 mb**

Seems like it is because of ctags was published with the package:
**520M** Apr 10 01:58 tags

Please unpublish this version and publish it again without it.

**Comment by silentroach** [comment]
ping @jaki

**Comment by silentroach** [comment]
ping @jakl

**Comment by pmarques** [comment]
:+1:

**Comment by satazor** [comment]
:+1:

**Comment by jakl** [comment]
Thanks for catching this, fixed.

**Comment by pmarques** [comment]
Thanks!

**Comment by jakl** [comment]
I added these files to .npmignore and published v1.13.2 to reduce the package size farther and prevent this from happening again:
+tags
+pkg/
+lib/
+test/
+tmp/
+chalkboard
+Rakefile
+Gruntfile.js

**Comment by silentroach** [comment]
Just use "files" array in the package.json - #80
