### ISSUE TITLE
Mentions don't include @ character

### ISSUE THREAD

**Issue by cristianrosu** [twitter/twitter-text#93]
When autoLink-ing tweets, @ sign is not included in mention

![mention_without_](https://cloud.githubusercontent.com/assets/1263233/11632535/4c8eaf5e-9d10-11e5-89bc-f0a06df92f84.png)

On twitter.com, @ sign is wrapped arround   s html tag so you can style it with a matching color. Is there any way to achieve this ?

**Comment by FMRb** [comment]
+1

**Comment by cristianrosu** [comment]
Awesome, I don't know how I've missed that. Thanks a bunch!

**Comment by xandrani** [comment]
&#64;foo renders on Twitter as:

`<a href="https://twitter.com/foo/"><s>&#64;</s><b>foo</b></a>
`

They then use CSS to underline 'a b' when hovering, and never to underline the 'a s'.

```
a b:hover {
   text-decoration: underline
}

a s {
   text-decoration: none
}
```

Check out example here: https://jsfiddle.net/MongooseOnTheMoon/Lq5kv04m/

Maybe there should be an alternative `autoLink()` function which renders it so it can be displayed properly?

[Note there seems to be a bug on GitHub... escaping an @ symbol as &amp;#64; etc doesn't work. It still picks it up as a potential username. The hash symbol also can't be escaped when you don't want it to be thought of as a hashtag]
