### ISSUE TITLE
Character count is off by one

### ISSUE THREAD

**Issue by rsliter** [twitter/twitter-text#94]
The [logic](https://github.com/twitter/twitter-text/blob/master/js/pkg/twitter-text-1.9.4.js#L1245-L1247) for tweets including URLs is such:

``` javascript
      // Add 23 characters for URL starting with https://
      // Otherwise add 22 characters
```

But [the docs](https://dev.twitter.com/rest/reference/get/help/configuration) suggest otherwise:

``` json
{
...

  "short_url_length": 23,
  "short_url_length_https": 23,
...
}
```

Would it be possible to simplify this logic to _always_ add 23 characters?

**Comment by twuttke** [comment]
Twitter changed its policy several months ago to convert all http links to
https, so there code is correct and the comment is outdated.

You could simplify the logic, yes. Anyone pulling in the new version might
have to make sure they weren't referencing old names.

**Comment by rsliter** [comment]
gotcha. so maybe the regexp the code is using is incorrect, then. for example:

```javascript
> twttr.txt.getTweetLength('http://bit.ly/1ckcXew');
< 22
```

whereas on twitter.com, pasting that same link evaluates to a length of 23 chars (117 remaining).

**Comment by twuttke** [comment]
twitter.com's internal version of getTweetlength already changed
short_url_length to 23, I wonder why that never made it back to the open
source repo?

  twttr.txt.getTweetLength = function(text, options) {
    if (!options) {
      options = {
          // These come from
https://api.twitter.com/1/help/configuration.json
          // described by
https://dev.twitter.com/docs/api/1/get/help/configuration
          short_url_length: 23,
          short_url_length_https: 23
      };
    }

You could do a pull request to change that one character from a 2 to a 3,
or you could yank some logic like this:

  // Returns the length of Tweet text with consideration to t.co URL
replacement
  // and chars outside the basic multilingual plane that use 2 UTF16 code
points
  twttr.txt.getTweetLength = function(text, options) {
    if (!options) {
      options = {
          // These come from
https://api.twitter.com/1/help/configuration.json
          // described by
https://dev.twitter.com/docs/api/1/get/help/configuration
          // All short urls are https now
          short_url_length: 23
      };
    }
    var textLength = twttr.txt.getUnicodeTextLength(text),
        urlsWithIndices = twttr.txt.extractUrlsWithIndices(text);
    twttr.txt.modifyIndicesFromUTF16ToUnicode(text, urlsWithIndices);

    for (var i = 0; i < urlsWithIndices.length; i++) {
      // Subtract the length of the original URL
      textLength += urlsWithIndices[i].indices[0] -
urlsWithIndices[i].indices[1];

      // Add 23 characters for short URLs
      textLength += options.short_url_length;
    }

    return textLength;
  };

And you may need to fix a unit test.

**Comment by gitbrook** [comment]
Any idea how can we can be kept in the loop to be notified when the URL length changes again?

**Comment by andypiper** [comment]
You could use the [API Changelog Twitter page](https://apichangelog.com/api/twitter) to subscribe to receive documentation changes, or follow the [Announcements on the Twitter Community](https://twittercommunity.com/c/announcements) developer forums.
