### ISSUE TITLE
Measure character count when including media

### ISSUE THREAD

**Issue by Sparragus** [twitter/twitter-text#95]
I can measure character count with no problem. But is the status will include media, I don't know how I can measure the correct character count of the status with the media.

Consider that in order to attach media to a tweet, you need to first upload it to Twitter and attach the media_id to the status' request to the API.

How can I accomplish that?

**Comment by andypiper** [comment]
This seems to be an API question which might be more suited to the developer forums at https://twittercommunity.com/

You should shorten the length of the character count by the current value of short_url_length_https from the /1.1/help/configuration.json endpoint. Currently this is 23 characters (the length of an HTTPS t.co link) so you have 140-23 = 117 characters to use in the status itself.

**Comment by Sparragus** [comment]
Thank you for your answer. I will try that today. Also I'm taking note of twittercommunity.com for future questions like this one. Cheers!
